version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Change to your app's port
    volumes:
      - ./app
       - node_modules:/usr/src/app/node_modules
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api
    networks:
      - app-network

  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "8000:8081" # Change to your website's port
    volumes:
      - ./website:/website
    networks:
      - app-network
    # watch:
    #     - action: sync
    #       path: ./website
    #       target: ./website
    #       ignore:
    #         - node_modules/
    #     - action: rebuild
    #       path: package.json

networks:
  app-network:
    driver: bridge
