version: '3.8'

services:
 
  api:
    image: bogdannrusu/fito-api:latest
    ports:
      - "4000:4000"
    volumes:
      - ./api:/api
    networks:
      - app-network

  website:
    image: bogdannrusu/fito-website:latest
    ports:
      - 3000:3000
    volumes:
      - ./website:/website
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
