version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Change to your app's port
    volumes:
      - ./app
       - node_modules:/usr/src/app/node_modules
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./api:/api
    networks:
      - app-network

  website:
    image: website
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./website:/website
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
